### ISSUE TITLE
plugin de warps para modo de juego survival

### ISSUE THREAD

**Issue by JerziOp** [BentoBoxWorld/Warps#112]
### Is your feature request related to a problem?

Hello, good day, I would like to know if it is possible for the warps plugin.
it is somehow compatible in the survival game mode, since I have a survival server and I would like to implement the warps plugin, without the need to have the skyblocks game mode.

I was wondering if this is possible and if so, I would really appreciate it if you could tell me how to do it, thank you and sorry for the inconvenience.

### Describe the solution you'd like.

I would like an answer that answers the question, is it possible to use the bentobox Warps plugin for a survival mode on a server, without having the skybloks game mode?

### Describe alternatives you've considered.

1.- if what I ask is not possible, I would be grateful if you could give me the name of a plugin that does what I ask
2.- develop a plugin that has the function for which I ask.
3.-do nothing

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported BentoBox build or Addons.

**Comment by JerziOp** [comment]
thank you for your attention, I hope what I ask is possible

**Comment by HSGamer** [comment]
Warps is for Skyblock-style servers only because it is the way to travel other islands.
If you want to add warps to your survival server, search "warps plugin spigot" on Google or just use EssentialsX.

**Comment by BONNe** [comment]
https://github.com/BentoBoxWorld/Warps/blob/develop/src/main/resources/config.yml#L26

But you still need BentoBox plugin.
