### ISSUE TITLE
Dublicated warps in panel

### ISSUE THREAD

**Issue by SirvydasS** [BentoBoxWorld/Warps#125]
### Expected behavior

Warps don't repeat showing on another page.

### Observed/Actual behavior

Warps repeat showing on another page.
Video: https://youtu.be/L_DI-wg4Aro

### Steps/models to reproduce

Have warps and simple write /ob warps and go to second page.

### BentoBox version

https://pastebin.com/QK4Qa2b5

### Other

Same problem with /ob phases (phase repeating on second page)

**Comment by BONNe** [comment]
This was a bug in BentoBox 1.24.1 release.
Fixed in this dev version: https://ci.codemc.io/job/BentoBoxWorld/job/BentoBox/2442/
