### ISSUE TITLE
Warp semi-working... kinda weird.

### ISSUE THREAD

**Issue by VirgilFabre** [BentoBoxWorld/Warps#32]
There's a sign on his island, it detect and create a welcome sign, but we can't TP to it, it says he doesn't have a sign...
Weird

BentoBox-1.6.0-SNAPSHOT-b1272
bskyblock-1.6.0-SNAPSHOT
warps-1.5.0

https://snag.gy/x9p4CV.jpg

Spigot 1.14.4 with BungeeCord

**Comment by tastybento** [comment]
Can you give me more information? I’m not clear on what’s happening.

**Comment by Nedjii** [comment]
I got some strange issues too with bentobox 1.7, when I remove my warp and place a new one it tells me duplicated sign, when I finally manage to place a warp it tells me there is no warp and when I manage to really put a warp there is just the player name on the sign, not what is written on the sign.

**Comment by Nedjii** [comment]
![2019-09-14_00 31 20](https://user-images.githubusercontent.com/30918460/64898328-038cd100-d687-11e9-86e6-5febba79a544.png)

**Comment by VirgilFabre** [comment]
Look like the same issue but with different details
Maybe he ll be able to locate the issue

**Comment by tastybento** [comment]
not sure its the same issue, but I fixed some bugs.

**Comment by Nedjii** [comment]
My issue with warp not defined seem to be fixed, however, the warp description in the GUI doesn't show up as it is on the sign.
![2019-09-14_22 09 00](https://user-images.githubusercontent.com/30918460/64913204-642a1580-d73c-11e9-867b-6eeb436ac66e.png)
![Uploading 2019-09-14_22.08.57.png…]()

**Comment by tastybento** [comment]
Does this aways happen? Or just with this colored text?

**Comment by Nedjii** [comment]
For some reason it works now, can I change the player name color in the GUI and the default text color ? (if the player doesn't put color on the sign)

**Comment by tastybento** [comment]
I made an enhancement issue for that. #48
