### ISSUE TITLE
Warp Version 1.6.0 There is no Warp.jar in the download

### ISSUE THREAD

**Issue by bow9500** [BentoBoxWorld/Warps#37]
**Description**
1.6.0 There is no Warp.jar in the download

**Steps to reproduce the behavior:**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/49287036/63319655-5c4da000-c34d-11e9-9526-002395dca815.png)

**Server Information:**

[Please complete the following information:]
 - Database being used (YAML, JSON, MySQL, MongoDB): []
 - Java Version: [e.g. Java 8]
 - BentoBox version: [e.g. 1.7.2.21]
 - Addons installed? [Do '/bentobox version' and copy/paste from the console]
 - Other plugins? [Do '/plugins' and copy/paste from the console]

**Additional context**

**Comment by osnapitzjamie** [comment]
pls fix so i can download it

**Comment by tastybento** [comment]
ok done
