### ISSUE TITLE
Label for Addon Request

### ISSUE THREAD

**Issue by Redemption2033** [BentoBoxWorld/Warps#39]
Sorry if this is somewhere, but I could not find it anywhere. It seems the javadocs are down and there's not much write up for the API for BentoBox.. What label would I use for an AddonRequest to get the location of the warp sign? I've figured out island-level was the one for Level, but can not figure out warp signs.

**Comment by BONNe** [comment]
There is no such thing implemented in Warps.
All Addon Requests are written in corresponding WIKI. If it is not, then it does not exist.

**Comment by Redemption2033** [comment]
> There is no such thing implemented in Warps.
> All Addon Requests are written in corresponding WIKI. If it is not, then it does not exist.

So is there no way to get the warp sign location with the API? I was able to do this with ASkyblock API before :/

**Comment by tastybento** [comment]
@Redemption2033 I added an API so you can request the data from the WarpSignsManager class. Have a look at the commit for the method names. You will need to cast the returned Object into the correct type. Let me know if you have any issues.
