### ISSUE TITLE
Adjusting material icons in /is warps GUI

### ISSUE THREAD

**Issue by wellnesscookie** [BentoBoxWorld/Warps#40]
### **Is your feature request related to a problem? Please describe.**
It is not!

### **Describe the solution you'd like**

It would be interesting to give player a permission to have a different icon than the default. For an example: **bskyblock.island.warp.icon.CLOCK** would set the display icon for the player in GUI to "CLOCK" instead of using the default sign material icon.

I'd say my idea is very cool to implement, because many owners care for how aesthetic their server is going to be. I think this is a step closer towards it. To be precise: we want to be able to give our ranked players a special icon that depends on the permission thay have set.

**Describe alternatives you've considered**
- Not manage by permissions, but with a command or so

## Visual display of my idea with permissions and icons:
**At the moment:**
![atm](https://user-images.githubusercontent.com/46493763/64078967-9b7ed800-cce1-11e9-9311-c071d33b56cf.png)

**How it would look if permissions feature was present:**
![after update](https://user-images.githubusercontent.com/46493763/64078970-a76a9a00-cce1-11e9-8a6b-813cbff68456.png)

**Comment by BONNe** [comment]
Cool Idea :D

**Comment by tastybento** [comment]
Nice idea. One note - permissions only can be checked when the player is online. Still, it's a nice idea.
