### ISSUE TITLE
create , no show in gui

### ISSUE THREAD

**Issue by p82183645** [BentoBoxWorld/Warps#43]
create is warps , no show in gui
i have test 

BentoBox-1.7.0-SNAPSHOT-b1362.jar
BSkyBlock-1.7.0-SNAPSHOT-b446.jar
WelcomeWarpSigns-1.6.2-SNAPSHOT-b179.jar

**Comment by tastybento** [comment]
I cannot replicate this problem. It works on my server okay.

Do **/bentobox version** in the console and share the output here.

**Comment by tastybento** [comment]
See https://youtu.be/htwmPKGlXNs

**Comment by tastybento** [comment]
Related to #46
