### ISSUE TITLE
SignChangeEvent Error

### ISSUE THREAD

**Issue by OverBrave** [BentoBoxWorld/Warps#45]
![image](https://user-images.githubusercontent.com/47111280/64472810-a8ca1580-d16c-11e9-809d-aa00a619cf6b.png)

#### Server
 - OS: **Windows**
 - Java version: **8**

#### Plugins

![image](https://user-images.githubusercontent.com/47111280/64472840-052d3500-d16d-11e9-87cf-a7c25203ea5a.png)

##### BentoBox and Addons
![image](https://user-images.githubusercontent.com/47111280/64472845-15451480-d16d-11e9-9bcc-31c2804765ea.png)

**Comment by tastybento** [comment]
This looks like an error due to reloading. 

Does it happen all the time? Or just once?

In general, don't reload. Restart the server.
