### ISSUE TITLE
Welcome sign not work 1.14.4

### ISSUE THREAD

**Issue by andris155** [BentoBoxWorld/Warps#46]
**Description**

**Steps to reproduce the behavior:**
1. Go to my island
2. Create Warp sign
3. Sign not created.

**Expected behavior**
Warp sign work

**Screenshots**
![2019-09-13_14 00 52](https://user-images.githubusercontent.com/8324198/64860937-ec21f980-d62e-11e9-9391-c487486c0192.png)

**Server Information:**

[Please complete the following information:]
 - Database being used (YAML, JSON, MySQL, MongoDB): JSON
 - OS: Ubuntu 18.04
 - Java Version: Java 11.0.4
 - BentoBox version: 1.7.0
 - Addons installed?
[14:02:26 INFO]: Running PAPER 1.14.4.
[14:02:26 INFO]: BentoBox version: 1.7.0
[14:02:26 INFO]: Database: JSON
[14:02:26 INFO]: Loaded Game Worlds:
[14:02:26 INFO]: acidisland_world (AcidIsland): Overworld, Nether, End
[14:02:26 INFO]: Loaded Addons:
[14:02:26 INFO]: AcidIsland 1.7.0-SNAPSHOT-b437 (ENABLED)
[14:02:26 INFO]: Biomes 1.6.0.2-SNAPSHOT-b141 (ENABLED)
[14:02:26 INFO]: Challenges 0.8.0-SNAPSHOT-#376 (ENABLED)
[14:02:26 INFO]: Greenhouses 0.4.0-SNAPSHOT (ENABLED)
[14:02:26 INFO]: Level 1.7.0-SNAPSHOT-b284 (ENABLED)
[14:02:26 INFO]: Limits 1.6.1-SNAPSHOT-b163 (ENABLED)
[14:02:26 INFO]: Warps 1.6.2-SNAPSHOT-b180 (ENABLED)
 - Other plugins?
Plugins (91): AdditionsAPI, AdminVedelem, AdvancedAchievements, antiRedstoneClock, AnvilRestrict, BentoBox, Brewery, BuntetesLogolo, ChangeSkin, ChatControl, ChatReaction, ChestCommands, ChestShop, ChestShopNotifier*, ChestSort, Citizens, CitizensCMD, CommandSigns, CompatNoCheatPlus*, ConditionalCommands*, CoreProtect, CraftBook, CratesPlus, CrazyAuctions, CrazyAuctionsLog, CustomCrafting, CustomOreGen, Duels, EnderContainers, EntityDetection, Ercgenerator, Essentials, EssentialsChat, EssentialsGeoIP, EssentialsSpawn, EventekGUI, EventRendszer, HeadDatabase*, HolographicDisplays, JukeBox, Kemkedes, Kezdes, LockettePro, Lottery, LuckPerms, mcMMO, MineMarket-Universal*, MobFarmManager, Multiverse-Core, Multiverse-NetherPortals, MyCommand, NametagEdit*, NoCheatPlus, NoSpawnerChange, NoteBlockAPI, OpenInv*, PickupSpawners, PlaceholderAPI*, PlayerHeads, PlugMan, PocketGames, PomaAdditions, ProtocolLib, RedstoneClockDetector, ShopGUIPlus, Shopkeepers, SignEdit*, StaffChat, StaffTime, Stats, Statscraft*, SuperLuckyBlock, Szilveszter, TiltottSzinek, TimeIsMoney*, TitleManager*, TokenManager, TokenStaff*, TreasureChestReloaded, VanillaAdditions, Vault, VillagerOptimiser, Votifier, VotingPlugin, WDLCompanion*, WolfyUtilities, WorldEdit, WorldGuard, WorldGuardExtraFlags, WorldGuardPomaFlags, YoutubeBridge

**Additional context**

**Comment by tastybento** [comment]
If you have Level installed, then you will need to meet the minimum level of island to be able to make a warp sign. You should have seen an error when you tried. The default level is 10. So, add some diamond blocks, do **/ai level** to get your level above 10 and then place a sign.

**Comment by tastybento** [comment]
There's a bug. Fixing now. Same issue as #47
