### ISSUE TITLE
is /warps don't work

### ISSUE THREAD

**Issue by leoncp9** [BentoBoxWorld/Warps#49]
Build #182
when i go to game and rty /is warps
i can't join to other islands
i can pickup item sign from menu
my server version is paperspigot 1.14.4
the problem str when i upèdate the plugin from build 181 to build#182

**Comment by tastybento** [comment]
Do `/bbox version` and share what is in console so I know what you have running.

**Comment by tastybento** [comment]
Also, make sure you restart and not reload the server.

**Comment by leoncp9** [comment]
now work, i update bentox and now is all fixed

**Comment by tastybento** [comment]
There is a bug with reloading for warps. I'm fixing it now. It causes double listening and weird things to happen, so see the next build.
