### ISSUE TITLE
warps delay

### ISSUE THREAD

**Issue by SirvydasS** [BentoBoxWorld/Warps#52]
**Is your feature request related to a problem? Please describe.**
No teleport delay when teleporting to warps. I have 3sec. bentobox(/is) delay but players can still be bypassed by that and example escape from the death when they go to is warp and then safe go to home (/is)
**Describe the solution you'd like**
When using command /is warp name or /is warps and then clicks on user signs (or random warp) from GUI it will need wait 3 seconds when he teleports. 

**Additional context**
Using latest version Warps and no message on warps random item it writes: warps.random.

**Comment by OverBrave** [comment]
This needs to be added immediately.
