### ISSUE TITLE
WelcomeWarps command override

### ISSUE THREAD

**Issue by AmazedMender16** [BentoBoxWorld/Warps#57]
**Description**
Welcome Warps 1.8.1 overrides the essentials warp commands even when the skyblock addon is used, can we get a toggle so it can work without skyblock and with skyblock?

Toggle on, works with /is warp but should not override /warp
Toggle off, override /warp and /warps command.

Yes, I'm aware of the config option to change the commands but that also changes the /is warp command.

**Comment by tastybento** [comment]
This is a bug. If the config setting `allow-in-other-worlds: false` is set then the command should not be registered. I'll fix.

**Comment by tastybento** [comment]
Please try the latest build.
