### ISSUE TITLE
Warp ...

### ISSUE THREAD

**Issue by W4RTR1X** [BentoBoxWorld/Warps#58]
I'm using paperspigot 1.13.2.
When i'm using /warp <name> not work because you do a command /warp in your plugin do /is warp for island warp dont use command /warp of essentials

**Comment by Poslovitch** [comment]
That's a bug in the latest release. Please use this [development build](https://ci.codemc.io/job/BentoBoxWorld/job/Warps/202/) for the time being.

**Comment by tastybento** [comment]
I've release version 1.8.2 now.
