### ISSUE TITLE
Name color

### ISSUE THREAD

**Issue by Nedjii** [BentoBoxWorld/Warps#61]
Hello, if you're using player head : icon: PLAYER_HEAD you can't set any color, it's using &e&o and there's no way to set another,
regards.

**Comment by tastybento** [comment]
I need more explanation. Which color and where?

**Comment by Nedjii** [comment]
You can set the name color in the warp gui, it works if you don't use player_head as item in the gui but if you use player_head it's turning yellow (&e&o) and you can't change the color.

**Comment by tastybento** [comment]
I just tested with the latest version of Warps and I cannot replicate this yet - it seems to work fine. Can you share `/bbox v`?

**Comment by Nedjii** [comment]
It has been fix with latest warps or bentobox version, I updated both.
