### ISSUE TITLE
Slow loading warp at startup

### ISSUE THREAD

**Issue by Malachiel87** [BentoBoxWorld/Warps#68]
**Description**
I imported askyblock warp with success, it work fine but i think at startup is a little slow (took 1 minute for load all warp, i attached here the file)

**Server Information:**
>....=>.... [16:57:04 INFO]: In esecuzione su PAPER 1.15.2.
>.... [16:57:04 INFO]: Versione BentoBox: 1.11.0
>.... [16:57:04 INFO]: Database: JSON
>.... [16:57:04 INFO]: Mondi di gioco caricati:
>.... [16:57:04 INFO]: askyblock (BSkyBlock): Overworld, [nether_color]Nether, [end_color]End
>.... [16:57:04 INFO]: Addons caricati:
>.... [16:57:04 INFO]: Biomes 1.6.0.1 (ENABLED)
>.... [16:57:04 INFO]: BSkyBlock 1.10.0 (ENABLED)
>.... [16:57:04 INFO]: Challenges 0.8.0 (ENABLED)
>.... [16:57:04 INFO]: ControlPanel 1.7.0 (ENABLED)
>.... [16:57:04 INFO]: DimensionalTrees 1.6.0 (ENABLED)
>.... [16:57:04 INFO]: Level 1.9.0 (ENABLED)
>.... [16:57:04 INFO]: Limits 1.9.0 (ENABLED)
>.... [16:57:04 INFO]: Warps 1.9.0 (ENABLED)

**Additional context**
Also when i open warp gui i see only 3 warp + random warp (not sure if is wanted) all warp work fine

**Comment by tastybento** [comment]
Okay. What is happening is that the addon is trying to read the warp sign content and that requires loading the chunk. How many warps do you have? I might have to switch them to be async.

**Comment by xion87** [comment]
Sorry forgot to attach the warp file
[warps.zip](https://github.com/BentoBoxWorld/Warps/files/4123953/warps.zip)

**Comment by Poslovitch** [comment]
It might be better to store the sign's content in the database, dont you think?

**Comment by Malachiel87** [comment]
any new about it?

**Comment by tastybento** [comment]
Yes, a commit was made back in January. What version are you using?

**Comment by Malachiel87** [comment]
warps-1.10.0.jar
