### ISSUE TITLE
Missing warp sign in gui

### ISSUE THREAD

**Issue by NotMyFault** [BentoBoxWorld/Warps#75]
**Description**

A few islands are missing a sign on the `/is warps` gui. Clicking the empty space works still, it just doesn't display a sign.

**Steps to reproduce the behavior:**
It just happened to a few islands.

**Expected behavior**
Displaying the sign placed

**Screenshots**
![](https://i.imgur.com/NYYxChh.png)
Slot 39 is missing, but clicking it teleports you to the warp sign of the island still.

![](https://i.imgur.com/q6MqRGL.png)
Warp sign on the island

**Server Information:**
Do `bbox version` in the console and paste the result here:
![](https://i.imgur.com/5WIhP2X.png)

**Additional context**
/

**Comment by tastybento** [comment]
Sorry for the late reply. Is this a random occurrence, or systematic? I might need a copy of your world and BentoBox folder to be able to replicate.

**Comment by N0tMyFaultOG** [comment]
It appears to be random. I couldn't find a way to reproduce that. 
My main world has a size of 160 gb . I don't think I can upload that anywhere.

**Comment by tastybento** [comment]
A warp icon can be air only when the warp location is checked and isn't a sign there anymore. I'm not sure how that can happen, but it looks like it can sometimes. Hmm.

**Comment by sgdc3** [comment]
Bump

**Comment by sgdc3** [comment]
Bump @tastybento

**Comment by sgdc3** [comment]
Any news on this? @tastybento

**Comment by tastybento** [comment]
Just busy with real-life stuff. Is the symptom the same as OP wrote? i.e., the warp sign is there, but the icon is blank?
