### ISSUE TITLE
Usable as standalone

### ISSUE THREAD

**Issue by FallingCactus** [BentoBoxWorld/Warps#77]
Hi,
   Not really a bug more of a suggestion...
I would love it if you could make the warps addon as a standalone plugin like it used to be on your Spigot years ago.
I use your warps on BentoBox gamemodes on my network but for my survival gamemodes we need to use something different but i would love to have player warp signs again so that we can have the same warp system for every server/gamemode across our network! 
I did try this as suggested by "Poslovitch" as they said it had been suggested before but adding BentoBox and warps addon to my survival server did not allow me to make a warp sign. I also tried it with "allow-in-other-worlds: true" with no luck.

Thanks

**Comment by tastybento** [comment]
`allow-in-other-worlds:true` is exactly the thing to use in that you would then get the `/warp` and `/warps` commands in other worlds. What didn't work for you?

**Comment by FallingCactus** [comment]
> `allow-in-other-worlds:true` is exactly the thing to use in that you would then get the `/warp` and `/warps` commands in other worlds. What didn't work for you?

so this should work on a server that does not have skyblock, acidislands ect on it? 
the setup I have in my survival server is bentobox plugin with only the warps add-on inside it but when I placed a sign and wrote [welcome] it didn't do anything. I will need to try again tomorrow as it's 1:30am for me, thanks for the reply

**Comment by FallingCactus** [comment]
This is the error i get from using command pwarps.
Error:
`18.05 07:24:20 [Server] INFO [11:24:20 INFO]: FallingCactus issued server command: /pwarps
18.05 07:24:20 [Server] Startup [11:24:20 ERROR]: null
18.05 07:24:20 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing 'pwarps' in world.bentobox.warps.commands.WarpsCommand(pwarps)
18.05 07:24:20 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.15.2.jar:git-Paper-260]
18.05 07:24:20 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:760) ~[patched_1.15.2.jar:git-Paper-260]
18.05 07:24:20 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1852) ~[patched_1.15.2.jar:git-Paper-260]
18.05 07:24:20 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1660) ~[patched_1.15.2.jar:git-Paper-260]
18.05 07:24:20 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-260]
18.05 07:24:20 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-260]
18.05 07:24:20 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-260]
18.05 07:24:20 [Server] INFO at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-260]
18.05 07:24:20 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-260]
18.05 07:24:20 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-260]
18.05 07:24:20 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-260]
18.05 07:24:20 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1093) ~[patched_1.15.2.jar:git-Paper-260]
18.05 07:24:20 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1086) ~[patched_1.15.2.jar:git-Paper-260]
18.05 07:24:20 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-260]
18.05 07:24:20 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1047) ~[patched_1.15.2.jar:git-Paper-260]
18.05 07:24:20 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-260]
18.05 07:24:20 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
18.05 07:24:20 [Server] INFO Caused by: java.lang.NullPointerException
18.05 07:24:20 [Server] INFO at world.bentobox.warps.commands.WarpsCommand.execute(WarpsCommand.java:46) ~[?:?]
18.05 07:24:20 [Server] INFO at world.bentobox.bentobox.api.commands.CompositeCommand.call(CompositeCommand.java:266) ~[?:?]
18.05 07:24:20 [Server] INFO at world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:239) ~[?:?]
18.05 07:24:20 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-260]
18.05 07:24:20 [Server] INFO ... 16 more`
Config:
`# WelcomeWarps Configuration 1.9.0
# This config file is dynamic and saved when the server is shutdown.
# You cannot edit it while the server is running because changes will
# be lost! Use in-game settings GUI or edit when server is offline.
# 
# 
# Warp Restriction - needed levels to be able to create a warp
# 0 or negative values will disable this restriction 10 is default
warplevelrestriction: 0
# 
# Text that player must put on sign to make it a warp sign
# Not case sensitive!
welcomeLine: '[Welcome]'
# 
# Icon that will be displayed in Warps list. SIGN counts for any kind of sign and the type of
# wood used will be reflected in the panel if the server supports it.
# It uses native Minecraft material strings, but using string 'PLAYER_HEAD', it is possible to
# use player heads instead. Beware that Mojang API rate limiting may prevent heads from loading.
icon: SIGN
# 
# This list stores GameModes in which Level addon should not work.
# To disable addon it is necessary to write its name in new line that starts with -. Example:
# disabled-gamemodes:
#  - BSkyBlock
disabled-gamemodes: []
# 
# Warp panel name formatting.
# Example: &c will make names red. &f is white
name-format: '&f'
# 
# Warp panel default lore formatting.
# Example: &c will make lore red. &f is white
lore-format: '&f'
# 
# Allow random teleport - adds a button to the warp panel that goes to a random warp sign
random-allowed: true
# 
# Allow use in other worlds. Players must have the welcomewarpsigns.warp permission.
allow-in-other-worlds: true
# 
# Warp and warps commands. You can change them if they clash with other addons or plugins.
warp-command: pwarp
warps-command: pwarps
`

**Comment by FallingCactus** [comment]
This is the error i get from using command pwarps.
Error:
https://hastebin.com/elijagilic.apache
Config:
https://hastebin.com/ahukabumig.shell

**Comment by tastybento** [comment]
@FallingCactus Weird - the links just show blank. Could you paste again?

**Comment by FallingCactus** [comment]
Weird, They show fine for me.
I'll use Pastebin this time around...
Error:
https://pastebin.com/aKYuVKGb
Config:
https://pastebin.com/ZUPsb3g8

**Comment by tastybento** [comment]
The hasten links now work... must have been a glitch in the matrix.

Try the latest build - https://github.com/BentoBoxWorld/Warps/releases/tag/1.9.4 I used your config file and I couldn't see the bug. If you still hit an issue let me know and share the result of `/bbox version` so I know what version of things you are using.

**Comment by FallingCactus** [comment]
Still having the same issue...
`20.05 11:08:00 [Server] Startup [15:08:00 INFO]: Running PAPER 1.15.2.
20.05 11:08:00 [Server] Startup [15:08:00 INFO]: BentoBox version: 1.13.1
20.05 11:08:00 [Server] Startup [15:08:00 INFO]: Database: JSON
20.05 11:08:00 [Server] Startup [15:08:00 INFO]: Loaded Game Worlds:
20.05 11:08:00 [Server] Startup [15:08:00 INFO]: Loaded Addons:
20.05 11:08:00 [Server] Startup [15:08:00 INFO]: Warps 1.9.4 (ENABLED)`

**Comment by tastybento** [comment]
Okay, I've replicated this issue. Now working to find out why it's happening.

**Comment by tastybento** [comment]
Should be fixed. Try 1.9.5 - https://github.com/BentoBoxWorld/Warps/releases/tag/1.9.5

**Comment by FallingCactus** [comment]
Can confirm this fixed the issue for me!

Thanks @tastybento
