### ISSUE TITLE
/warp blocking Essentials's /warp command

### ISSUE THREAD

**Issue by immakita** [BentoBoxWorld/Warps#79]
I'm using Warp addon for AOneBlock. But on my server warps addon blocking essentials's warp command.

we must use /ob warp or /is warp (for BSkyBlock) 

[21:45:29 INFO]: Sunucu PAPER 1.15.2 sürümünde çalışıyor.
[21:45:29 INFO]: BentoBox sürümü: 1.13.1
[21:45:29 INFO]: Database: JSON
[21:45:29 INFO]: Yüklenen oyun dünyaları:
[21:45:29 INFO]: oneblock (OneBlock): Overworld
[21:45:29 INFO]: Yüklenen eklentiler:
[21:45:29 INFO]: AOneBlock 1.1.7
[21:45:29 INFO]: Chat 1.0.5
[21:45:29 INFO]: Likes 1.7.1
[21:45:29 INFO]: Warps 1.9.5

**Comment by tastybento** [comment]
What is your Warps config.yml? There is a setting in there that enables it to run as the `/warp` command and to set what the command is. So check this section:
```
# Allow use in other worlds. Players must have the welcomewarpsigns.warp permission.
allow-in-other-worlds: false 
#
# Warp and warps commands. You can change them if they clash with other addons or plugins.
warp-command: warp
warps-command: warps
```

**Comment by immakita** [comment]
When I change the commands, we have to write it as 

> / ob [New Command]

. This looks bad.

**Comment by tastybento** [comment]
Sorry, I don’t understand. What do you want it to do?

**Comment by immakita** [comment]
When we type "/warp" it conflicts with Essentials and Essentials "/warp" command doesn't work. The Warp Plugin works instead.
I don't want this, and it looks bad when I change the command.

**Comment by tastybento** [comment]
If you don't want this then set:
```
# Allow use in other worlds. Players must have the welcomewarpsigns.warp permission.
allow-in-other-worlds: false 
```

**Comment by BONNe** [comment]
Well, tasty, issue is that he wants to use it as a standalone plugin but it conflicts with essentials commands.

**Comment by tastybento** [comment]
If he wants to use it as a standalone plugin, but it conflicts with the Essentials commands then the solution is to change the command to something else (like it says in the comments):

```
# Allow use in other worlds. Players must have the welcomewarpsigns.warp permission.
allow-in-other-worlds: true
# Warp and warps commands. You can change them if they clash with other addons or plugins.
warp-command: pwarp
warps-command: pwarps
```

This will change it to `/pwarp` and `/pwarps`.

**Comment by tastybento** [comment]
If you want `/warp` to override the Essentials warp then maybe you can do this by removing the Essentials warp permission from players.
