### ISSUE TITLE
Warp gui text sign doesn't update

### ISSUE THREAD

**Issue by x1p** [BentoBoxWorld/Warps#80]
**Description**

The text in the warp gui does not reflect the text on the signs of players warps.
Some players have text under `[Warp]` which ends up in the gui.

How can I force an update on the warps gui?

**Steps to reproduce the behavior:**
1. Players make warp signs
2. Players destroy sign
3. Check to see if the sign is deleted from the gui screen
4. Players make sign again using different text
5. /is warps shows old text.
6. Players destroy sign
7. Check to see if the sign is deleted from the gui screen
8. Players make sign again using different text
9. /is warps shows old text.
10. Server restart does not help.

**Expected behavior**

I would expect that deleting and (re)creating a sign would update the text of the signs in the `/is warps` gui.

**Screenshots**

![Screenshot_20200527_194237](https://user-images.githubusercontent.com/28690790/83054199-5316ff80-a052-11ea-805c-7e8a75c3a972.png)
![Screenshot_20200527_194443](https://user-images.githubusercontent.com/28690790/83054324-8ce80600-a052-11ea-959b-b298fb08a942.png)

**Server Information:**
Do `bbox version` in the console and paste the result here:
Running PAPER 1.15.2.
BentoBox version: 1.14.0-SNAPSHOT-b1796
Database: JSON
Loaded Game Worlds:
bskyblock_world (BSkyBlock): Overworld, Nether, The End
Loaded Addons:
Biomes 1.12.0-SNAPSHOT-b160 (ENABLED)
BSkyBlock 1.13.1 (ENABLED)
Challenges 0.9.0-SNAPSHOT-b416 (ENABLED)
Level 2.0.0 (ENABLED)
Limits 1.12.2 (ENABLED)
MagicCobblestoneGenerator 1.9.0-SNAPSHOT-b102 (ENABLED)
Warps 1.9.5 (ENABLED)

**Additional context**

No errors or clues on the console.

**Comment by tastybento** [comment]
This is a bug. It looks like the cache isn't being cleared when the sign is removed for some reason.

**Comment by tastybento** [comment]
Weird. I cannot replicate right now. Can you share your database for Warps, please? (Zip up and drop into this reply)

**Comment by x1p** [comment]
Sure
[database.zip](https://github.com/BentoBoxWorld/Warps/files/4691751/database.zip)

**Comment by tastybento** [comment]
Please try the latest build from the CI server. Also, as your cache has become out of sync, stop the server and delete/move the database/SignCache folder from the database so it can be regenerated.
