### ISSUE TITLE
Don't send chat message when teleporting vanished

### ISSUE THREAD

**Issue by piotrskibapl** [BentoBoxWorld/Warps#87]
**Is your feature request related to a problem? Please describe.**
As an admin, I would sometimes like to teleport to the players warp. However, the current behavior of this addon would tell the warp owner that I teleported to it, even when I'm vanished.

**Describe the solution you'd like**
The message that someone teleported to your island could be not sent if you can't see that player.

**Describe alternatives you've considered**
There could be also an option in the config to disable these messages completely.

**Comment by tastybento** [comment]
Please try 1.10.1-SNAPSHOT on https://ci.bentobox.world when it's ready and see if that works for you.

**Comment by piotrskibapl** [comment]
It works great. Thanks a lot!
