### ISSUE TITLE
(feature) Add destination to 'user warped to your warp sign'

### ISSUE THREAD

**Issue by mrfloris** [BentoBoxWorld/Warps#89]
**Is your feature request related to a problem? Please describe.**

`It would be more descriptive if it didn't say warped to warp, but actually inform the user where they warped to`

**Describe the solution you'd like**

`add destination to to the message 'user warped to your warp sign', for example: User has warped to your oneblock island`

**Describe alternatives you've considered**

`add placeholder to locale entry to cover al game modes at once`

**Additional context**

`i like milk`

**Comment by tastybento** [comment]
Good idea. I’ll try and work on it this holiday.
