### ISSUE TITLE
(Feature) API - getOwner() in WarpRemoveEvent

### ISSUE THREAD

**Issue by Kryniowesegryderiusz** [BentoBoxWorld/Warps#91]
**Is your feature request related to a problem? Please describe.**
I need for my own addon getting owner instance of Player of removed sign in WarpRemoveEvent. I'd love to see that <3

**Comment by tastybento** [comment]
As the only player who can remove their sign is the sign's owner, the UUID of the owner is found by `getRemover()`

**Comment by Kryniowesegryderiusz** [comment]
Not really
https://github.com/BentoBoxWorld/Warps/blob/86612b72e36f32412480c8b51290e471f91ebc9e/src/main/java/world/bentobox/warps/listeners/WarpSignsListener.java#L125

**Comment by tastybento** [comment]
Okay, good point. I'll fix it.

**Comment by tastybento** [comment]
Let me know if that works for you.

**Comment by Kryniowesegryderiusz** [comment]
Maybe I'm doing something wrongly, but when I import warps as dependency it doesnt show me this method.

**Comment by tastybento** [comment]
It's still in the development branch, so if you are using Maven then you need to use the SNAPSHOT until I release:

```
        <dependency>
            <groupId>world.bentobox</groupId>
            <artifactId>Warps</artifactId>
            <version>Warps-1.11.0-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
```

Make sure you have the snapshot repo in you pom.xml:

```
        <repository>
            <id>codemc</id>
            <url>https://repo.codemc.org/repository/maven-snapshots/</url>
        </repository>
```
