### ISSUE TITLE
Missing warps after update

### ISSUE THREAD

**Issue by Kesims** [BentoBoxWorld/Warps#92]
**Description**

After last update warp menu is missing some warps. Places that are not filled with sign return missing warp message in chat.

**Steps to reproduce the behavior:**
Upgrade bentoBox and addons to latest versions

**Expected behavior**

Clear blank spaces/show warps

**Screenshots**

![obrazek](https://user-images.githubusercontent.com/43478239/103543667-32900d00-4e9f-11eb-9635-2582d51fba29.png)

**Server Information:**
Do `bbox version` in the console and paste the result here:
![obrazek](https://user-images.githubusercontent.com/43478239/103543739-49cefa80-4e9f-11eb-8581-b18a542a6d7a.png)

**Comment by Kesims** [comment]
Update: the blank places are probbalby warps of people, that have warp sign, but it somehow deleted it in /is warps

**Comment by tastybento** [comment]
What version were you using before the update to 1.10.2?

It looks like the SignCache does not have those signs in it, so they need to be added somehow.

To help me, can you share the following:

1. A zip of your island world. I realize this will be big, but it will enable me to replicate the issue. Please use DropBox or something to share. I will keep it confidential. If you want to send me the link via email send to tastybento (at) bentobox.world
2. A zip of BentoBox/database/WarpsData and BentoBox/database/SignCache.

**Comment by Kesims** [comment]
Before 1.10.2 I have been using 1.9.7

World zip: https://drive.google.com/file/d/1h8d8hofuqjLrTUE_-hsCbRUHG2LB3QCe/view?usp=sharing
SignCache zip: https://drive.google.com/file/d/1OTEYvi-qIvD_4hicMExwm8w8ic8Eb-hO/view?usp=sharing
WarpsData zip: https://drive.google.com/file/d/1KEtumWJKvKW1t3gdC5G9NRHbPbL0tFO2/view?usp=sharing

**Comment by tastybento** [comment]
I'll check this weekend.
