### ISSUE TITLE
Player Warp Isn't Removed When Another Player Breaks Block Below Sign

### ISSUE THREAD

**Issue by meowsome** [BentoBoxWorld/Warps#97]
#### Describe the bug
I had a player on my server report this. When you have another player trusted on your island, and that player breaks the block below a [WELCOME] sign that you create, the sign is removed but the warp remains in the GUI menu. 

#### Steps to reproduce the behavior
1. Create an island and create a warp sign
2. Add another player to your island
3. Other player breaks the block below your warp sign

#### Expected behavior
The player whose sign was broken should no longer have a warp in the GUI menu. 

#### Screenshots and videos (Optional)
N/A

##### Output of `/bbox version` (Mandatory)
```
[12:36:25 INFO]: Running PAPER 1.16.1.
[12:36:25 INFO]: BentoBox version: 1.15.1
[12:36:25 INFO]: Database: JSON
[12:36:25 INFO]: Loaded Game Worlds:
[12:36:25 INFO]: prison_cells (Cells): Overworld
[12:36:25 INFO]: Loaded Addons:
[12:36:25 INFO]: BSkyBlock 1.14.0 (ENABLED)
[12:36:25 INFO]: Limits 1.14.0 (ENABLED)
[12:36:25 INFO]: Warps 1.10.0 (ENABLED)
```

#### Plugins (Optional)
N/A
 
### Additional context (Optional)
This can be temporarily fixed if the player places another [WELCOME] sign and then breaks the sign themselves.

**Comment by tastybento** [comment]
This is a known issue. If the player tries to use the warp it won't work and the warp will be removed at that point. Unfortunately, there isn't a way that is efficient to check for this kind of block break (there is but it requires using the BlockPhysicsEvent which occurs so many times that it could cause exceptional lag).
So long as the warp doesn't work when someone tries to use it, this is not something that will be fixed right now.
